header:
    #version: 3
config:
    service-perftool-kafka:
        type: kafka
        brokers: "broker:9092"
        topic: topic-perftool-kafka

    service-perftool-mqtt:
        type: mqtt
        brokers: "broker:1883"
        topic: topic-perftool-mqtt
